- name: Nginx web server
  apt:
    name: nginx
    update_cache: yes

- name: Copy html file to server
  ansible.builtin.copy:
    src: /Users/annelivali/Desktop/ica0002/roles/nginx/files/default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx
