- name: Install influxdb stats exporter
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influx_stats_exporter
    mode: 0555

- name: Copy conf
  ansible.builtin.copy:
    src: prometheus-influxdb-stats-exporter.service
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify: 
    - Restart influxdb stats exporter
    - Reload systemd

- name: Prometheus
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes
  