- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy

- name: Haproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Haproxy started
  ansible.builtin.service:
    name: haproxy
    state: started

- name: Install haproxy-exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter

- name: Haproxy-exporter config
  ansible.builtin.template:
    src: haproxy_exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart haproxy-exporter

- name: Start haproxy exporter
  ansible.builtin.service:
      name: prometheus-haproxy-exporter
      state: started
      enabled: yes
