- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal stable

- name: Install influxdb
  ansible.builtin.apt:
    name: influxdb

- name: Influxdb conf
  ansible.builtin.copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify: Restart influxdb

- name: Start service influxdb
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: yes

- name: Intsall telegraf
  ansible.builtin.apt:
    name: telegraf

- name: Telegraf conf
  ansible.builtin.copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Start service telegraf
  service:
    name: telegraf
    state: started
    enabled: yes