- name: Start rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes

- name: Copy rsyslog conf
  ansible.builtin.template:
    src: telegraf.conf
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog