- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install grafana
  ansible.builtin.apt:
    name: grafana
  notify: Change password for grafana user

- name: Start service grafana
  service:
      name: grafana-server
      state: started
      enabled: yes
  
- name: Move conf
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Move prometheus data source
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
  notify: Restart grafana

- name: Move influxdb data source
  ansible.builtin.template:
    src: influxdb.yaml.j2
    dest: /etc/grafana/provisioning/datasources/influxdb.yaml
  notify: Restart grafana
  
- name: Move influxdb telegarf data source
  ansible.builtin.template:
    src: influxdbtelegraf.yaml.j2
    dest: /etc/grafana/provisioning/datasources/influxdbtelegraf.yaml
  notify: Restart grafana
  
- name: Move dasboard conf
  ansible.builtin.template:
    src: dashboard.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana

- name: Move main dasboard json
  ansible.builtin.copy:
    src: main.json
    dest: /etc/grafana/provisioning/dashboards/main.json
  notify: Restart grafana

- name: Move syslog dasboard json
  ansible.builtin.copy:
    src: syslog.json
    dest: /etc/grafana/provisioning/dashboards/syslog.json
  notify: Restart grafana
