- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: grafana
  ansible.builtin.apt:
    name: grafana
  notify: Change password

- name: Start grafana
  service:
      name: grafana-server
      state: started
      enabled: yes
  
- name: Move conf
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Move data source
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
  notify: Restart grafana
  
- name: Move dasboard 
  ansible.builtin.template:
    src: dashboard.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana

- name: Move dasboard json
  ansible.builtin.copy:
    src: main.json
    dest: /etc/grafana/provisioning/dashboards/main.json
  notify: Restart grafana
