- name: Install packages 
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: Start service
  service:
    name: uwsgi
    state: started
    enabled: yes

- name: Copy agama conf
  template:
    src: /Users/annelivali/Desktop/ica0002/roles/uwsgi/templates/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    mode: 0644
  notify: Restart uWSGI
