- name: Install packages 
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: Start service
  service:
    name: uwsgi
    state: started
    enabled: yes

- name: Copy agama conf
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    mode: 0644
  notify: Restart uWSGI
