- name: Create user agama
  ansible.builtin.user:
    name: agama

- name: Create a directory 
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    mode: 0755
    owner: agama
  
- name: Install dependencies for agama
  ansible.builtin.apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Install agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: 0644
