- name: Create backup user
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes

- name: Create directory
  ansible.builtin.file:
    path: /home/backup/restore
    owner: backup
    mode: 0644
    state: directory

- name: Install duplicity
  ansible.builtin.apt:
    name: duplicity

- name: Move conf of known hosts
  ansible.builtin.template:
    owner: backup
    group: backup
    mode: 0644
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    
