- name: Create directory
  ansible.builtin.file:
    path: /home/backup/influxdb
    owner: backup
    mode: 0755
    state: directory

- name: Move conf
  ansible.builtin.template:
    src: influxdb-backup
    dest: /etc/cron.d/influxdb-backup
    