- name: Restart keepalived
  ansible.builtin.service:
      name: keepalived
      state: restarted

- name: Reload systemd
  ansible.builtin.shell: systemctl daemon-reload

- name: Restart prometheus-keepalived-exporter
  ansible.builtin.service:
      name: prometheus-keepalived-exporter
      state: restarted