- name: mysql
  ansible.builtin.apt:
    name: 
      - mysql-server
      - python3-pymysql

- name: Started service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Copy override to location
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: Restart mysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
