- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived

- name: Keepalived config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Keepalived config
  ansible.builtin.template:
    src: haproxy88.j2
    dest: /usr/local/bin/haproxy88
    mode: 755

- name: Keepalived started
  ansible.builtin.service:
    name: keepalived
    state: started
