  - name: Install nginx-exporter
    apt:
      name: prometheus-nginx-exporter
      state: latest

  - name: Start nginx-exporter
    service:
        name: prometheus-nginx-exporter
        state: started
        enabled: yes

