- name: Restart grafana
  ansible.builtin.service:
      name: grafana-server
      state: restarted

- name: Change password
  shell: |
    sleep 30
    grafana-cli admin reset-admin-password {{grafana_pass}}
    