- name: Iptable fix
  ansible.builtin.template:
    src: tablefix
    dest: /var/local/iptables.mangle

- name: Iptable state
  community.general.iptables_state:
    path: /var/local/iptables.mangle
    state: restored
    table: mangle
  poll: 0
  async: 5

- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent

- name: Saving iptables rules over reboot
  ansible.builtin.template:
    src: tablefix
    dest: /etc/iptables/rules.v4

- name: Install docker package
  ansible.builtin.apt:
    name: 
      - docker.io
      - python3-docker

- name: Started service docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
  no_log: True
