- name: bind9
  ansible.builtin.apt:
    name: bind9

- name: Start bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: Move bind9 conf
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Move db conf
  ansible.builtin.template:
    src: db.boom
    dest: /var/cache/bind/db.boom
  notify: Reload bind9

- name: Move local conf
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9
