- name: Install bind9 and dns features
  ansible.builtin.apt:
    name: 
      - bind9
      - python3-dnspython

- name: Move bind9 conf
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  no_log: True
  notify: Restart bind9

- name: Move startup and reversed db conf
  when: inventory_hostname in groups['dns_master']
  ansible.builtin.template:
    src: db.{{item}}
    dest: /var/cache/bind/db.{{item}}
    force: no
  loop:
    - "{{startup_name}}"
    - 42.168.192.in-addr.arpa

- name: Move local conf
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  no_log: True
  notify: Restart bind9

- name: Start bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes
