- name: bind9
  apt:
    name: bind9

- template:
    src: named.conf.objects.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- template:
    src: db.boom
    dest: /var/cache/bind/db.boom
  notify: Reload bind9 

- template:
    src: name.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9
